name: Daily-Build
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

        - name: Show Current Time and Date
          run: date -u
        - name: Checkout Code
          uses: actions/checkout@v5

        - name: Set up Node JS
          uses: actions/setup-node@v5
          with:
            node-version: '20.19.0'
            
        - name: Install Dependencies
          run: rm -rf node_modules package-lock.json && npm install
          
        - name: Run tests
          run: npm test

        - name: Build React App
          run: npm run build