# name: Daily Build

# on:
#   schedule:
#     - cron: "*/5 * * * *"
#   workflow_dispatch: 
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:

#       - name: Show Current Time and Date
#         run: date -u

#       - name: Checkout Code
#         uses: actions/checkout@v5

#       - name: Set up Node JS
#         uses: actions/setup-node@v5
#         with:
#           node-version: '20.19.0'
      
#       - name: Install Dependencies
#         run: rm -rf node_modules package-lock.json && npm install

#       - name: Run tests
#         run: npm test

#       - name: Build Project
#         run: npm run build  

#       - name: Upload Build Artifacts
#         uses: actions/upload-artifact@v4
#         with:
#           name: react-build
#           path: dist

#       # ✅ Send email on success
#       - name: Send Email Notification (Success)
#         if: success()
#         uses: betterfor/action-send-mail@main
#         with:
#           server_address: smtp.gmail.com
#           server_port: 465
#           username: ${{ secrets.EMAIL_USERNAME }}   # must be full Gmail address
#           password: ${{ secrets.EMAIL_PASSWORD }}   # must be Gmail app password
#           subject: "✅ Build Successful: React App CI"
#           to: vinitranjan262000@gmail.com
#           from: ${{ secrets.EMAIL_USERNAME }}
#           body: |
#             Build job of ${{ github.repository }} completed successfully.
#             Commit: ${{ github.sha }}
#             Run ID: ${{ github.run_id }}

#       # ✅ Send email on failure
#       - name: Send Email Notification (Failure)
#         if: failure()
#         uses: betterfor/action-send-mail@main
#         with:
#           server_address: smtp.gmail.com
#           server_port: 465
#           username: ${{ secrets.EMAIL_USERNAME }}
#           password: ${{ secrets.EMAIL_PASSWORD }}
#           subject: "❌ Build Failed: React App CI"
#           to: vinitranjan262000@gmail.com
#           from: ${{ secrets.EMAIL_USERNAME }}
#           body: |
#             Build job of ${{ github.repository }} failed.
#             Commit: ${{ github.sha }}
#             Run ID: ${{ github.run_id }}
